language: node_js

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

before_install:
    - export CXX="g++-4.8"
    - npm install juttle@0.6.x
    - curl -L -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.1.1/elasticsearch-2.1.1.tar.gz
    - tar -xvf elasticsearch-2.1.1.tar.gz
    - rm elasticsearch-2.1.1.tar.gz
    - ./elasticsearch-2.1.1/bin/elasticsearch &

node_js:
    - '4.2'
    - '5.0'

before_script:
    - npm install -g eslint

script:
    - npm test
    - npm run -s check-coverage
